## 1.

In [1]:
# Ordinal encoding, which turns each label into an integer value and depicts the sequence of labels in the encoded data,
# is employed when the variables in the data are ordinal.

# If we have any data with some categorical value like color then we take ordinal encoding.

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
import seaborn as sns

df=sns.load_dataset('tips')
df.head()
ord_Encoder=encoder.fit_transform(df[['time']])
ord_Encoder  # here the dinner has converted into 0 and lunch has 1.

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [3]:
# Label Encoding is a technique that is used to convert categorical columns into numerical ones so that they can be fitted by 
# machine learning models which only take numerical data.

# It is an important pre-processing step in a machine-learning project.

In [4]:
df.head()
df['day'].unique()


from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [6]:
encoder.fit_transform(df[['day']])

# it has lanbeled as 
# Friday: 0
# sat: 1
# sun:2
# thur:3

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

## 2.unique

In [7]:
# In this technique we will take help of our target variable to encode the categorical data 

In [8]:
import seaborn as sns
df=sns.load_dataset('tips')
df.head()
df['time'].unique()
mean_1=df.groupby('time')['total_bill'].mean()
df['new']=df['time'].map(mean_1)


# In this we targetted time with total_bill.


In [9]:
df

total_bill   tip     sex smoker   day    time  size        new
0         16.99  1.01  Female     No   Sun  Dinner     2  20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3  20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3  20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2  20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4  20.797159
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2  20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2  20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2  20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2  20.797159

[244 rows x 8 columns]

## 3.

In [10]:
# Covariance is a statistical tool used to determine the relationship between the movements of two random variables.
# When two stocks tend to move together, they are seen as having a positive covariance; when they move inversely, the covariance is negative

In [11]:
# Positive Covariance:
# A positive covariance between two variables indicates that these variables tend to be higher or lower at the same time.
# In other words, a positive covariance between stock one and two is where stock one is higher than average at the same points that stock two is higher than average, and vice versa.
# When charted on a two-dimensional graph, the data points will tend to slope upwards.

In [12]:
# Negative Covariance:
# When the calculated covariance is less than negative, this indicates that the two variables have an inverse relationship. 
# In other words, a stock one value lower than average tends to be paired with a stock two value greater than average, and vice versa.

## 4.

In [13]:
import pandas as pd
df=pd.DataFrame({'color':['red','green','blue'],
             'size':['small','medium','large'],
             'material':['wood','metal','plastic']})

In [14]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
lab_encoder=LabelEncoder()
ord_encoder=OrdinalEncoder()

In [15]:
encode_color=ord_encoder.fit_transform([['red'],['green'],['blue']]) 
encode_size=ord_encoder.fit_transform([['small'],['medium'],['large']])
encode_material=lab_encoder.fit_transform(['wood','metal','plastic'])

In [16]:
encode_color

array([[2.],
       [1.],
       [0.]])

In [17]:
encode_material

array([2, 0, 1])

In [18]:
encode_size

array([[2.],
       [1.],
       [0.]])

In [19]:
df

color    size material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [20]:
df['new_color']=encode_color
df['new_size']=encode_size
df['new_material']=encode_material

In [21]:
df

color    size material  new_color  new_size  new_material
0    red   small     wood        2.0       2.0             2
1  green  medium    metal        1.0       1.0             0
2   blue   large  plastic        0.0       0.0             1

## 5.

In [22]:
# Covariance Matrix is a measure of how much two random variables gets change together. It is actually used for computing the covariance in between every column of data matrix.
# The Covariance Matrix is also known as dispersion matrix and variance-covariance matrix.

In [23]:
import pandas as pd

In [24]:
df=pd.DataFrame({'Age':[20,30,40,50],
             'Income':[1000,2000,3000,4000],
             'Education':[4,3,2,1]})

In [25]:
import numpy as np

In [26]:
np.cov(df)

array([[ 325445.33333333,  653340.66666667,  981236.        ,
        1309131.33333333],
       [ 653340.66666667, 1311606.33333333, 1969872.        ,
        2628137.66666667],
       [ 981236.        , 1969872.        , 2958508.        ,
        3947144.        ],
       [1309131.33333333, 2628137.66666667, 3947144.        ,
        5266150.33333333]])

## 6.

In [27]:
# Gender:Binary encoding.
# because it has only 2 variables.

# Education level:Ordinal encoding.
# because it has a order due to his grades and his high values.

# Employment status:Label encoder.
# it has no ranking so we use just a label to  conver tnumerical values.
