## 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(object=list)

In [4]:
array_list

array(<class 'list'>, dtype=object)

In [18]:
(array_list)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

## 2.

In [11]:
type(list_[0])

str

In [26]:
array_list.dtype

dtype('O')

## 3.

In [30]:
array_list=np.array(object=list_,dtype=int)

In [31]:
array_list

array([1, 2, 3, 4, 5])

In [32]:
list_

['1', '2', '3', '4', '5']

In [34]:
type(list_[1])

str

In [35]:
type(array_list[1])

numpy.int64

In [36]:
###


In [37]:
import numpy as np

In [40]:
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)

In [41]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [42]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.shape(num_list)

(2, 3)

In [45]:
np.shape(num_array)

(2, 3)

In [46]:
np.size(num_list)

6

In [47]:
np.size(num_array)

6

## 5.  

In [49]:
import numpy as np

In [54]:
a=np.zeros([3,3])

In [55]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.size(a)

9

## 6.

In [57]:
a=np.eye(5,5)

In [58]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])